apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 65.1.1
    helm:
      releaseName: kube-prometheus-stack
      values: |
        crds:
          enabled: false
        kubeScheduler:
          serviceMonitor:
            insecureSkipVerify: true
        kubeEtcd:
          tlsConfig:
            insecureSkipVerify: true     
        kubeApiServer:
          tlsConfig:
            insecureSkipVerify: true
        grafana:
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - grafana.ganba.local
        prometheus:
          prometheusSpec:
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: local-path
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 10Gi
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - prometheus.ganba.local

  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-prometheus-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true