apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 65.1.1
    helm:
      releaseName: kube-prometheus-stack
      values: |
        kubeScheduler:
          serviceMonitor:
            insecureSkipVerify: true
        kubeEtcd:
          tlsConfig:
            insecureSkipVerify: true     
        kubeApiServer:
          tlsConfig:
            insecureSkipVerify: true
        grafana:
          ingress:
            enabled: true
            hosts:
              - grafana.localhost
        prometheus:
          ingress:
            enabled: true
            hosts:
              - prometheus.localhost

  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-prometheus-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true