apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/david-bour/local-gitops.git
      revision: HEAD
      directories:
      - path: argocd-applications/apps/*/envs/dev
  template:
    metadata:
      name: '{{index .path.segments 2}}-{{index .path.segments 4}}' 
      annotations:
        argocd-image-updater.argoproj.io/image-list: echoapp=davidbour/echoserver
        argocd-image-updater.argoproj.io/echoapp.update-strategy: newest-build
        argocd-image-updater.argoproj.io/echoapp.allow-tags: regexp:^[0-9a-f]{40}$
    spec:
      project: default
      source:
        repoURL: https://github.com/david-bour/local-gitops.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{index .path.segments 2}}-{{index .path.segments 4}}' 
      syncPolicy:
        syncOptions:
          - CreateNamespace=true  
        automated:
          prune: true
          selfHeal: true
