apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-applicationset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - index: 1
      - index: 2
      - index: 3
      - index: 4
      - index: 5
      - index: 6
      - index: 7
      - index: 8
      - index: 9
      - index: 10
      - index: 11
      - index: 12
      - index: 13
      - index: 14
      - index: 15
      - index: 16
      - index: 17
      - index: 18
      - index: 19
      - index: 20
      - index: 21
      - index: 22
      - index: 23
      - index: 24
      - index: 25
      - index: 26
      - index: 27
      - index: 28
      - index: 29
      - index: 30
      - index: 31
      - index: 32
      - index: 33
      - index: 34
      - index: 35
      - index: 36
      - index: 37
      - index: 38
      - index: 39
      - index: 40
  goTemplate: true
  goTemplateOptions:
  - missingkey=error
  template:
    metadata:
      name: nginx-applicationset-{{.index}}
    spec:
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: default
      source:
        helm:
          values: 'suffix: {{.index}}'
        path: argocd-applications/applications/nginx
        repoURL: https://github.com/david-bour/local-gitops.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
