apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-applicationset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - index: "1"
      - index: "2"
  template:
    metadata:
      name: 'nginx-{{.index}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/david-bour/local-gitops.git
        path: argocd-applications/applications/nginx
        targetRevision: HEAD
      destination:
        server: "https://kubernetes.default.svc"
        namespace: argocd
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
