apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-applicationset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - index: "1"
      - index: "2"
      - index: "3"
      - index: "4"
      - index: "5"
  template:
    metadata:
      name: 'nginx-{{.index}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/david-bour/local-gitops.git
        path: argocd-applications/applications/nginx
        targetRevision: HEAD
        helm:
          values: |
            suffix: {{.index}}
      destination:
        server: "https://kubernetes.default.svc"
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
