apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-applicationset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - index: 1
  goTemplate: true
  goTemplateOptions:
  - missingkey=error
  template:
    metadata:
      name: nginx-applicationset-{{.index}}
    spec:
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: default
      source:
        helm:
          values: 'suffix: {{.index}}'
        path: argocd-applications/applications/nginx
        repoURL: https://github.com/david-bour/local-gitops.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
