appname: happy-cat
image:
  repository: davidbour/echoserver
  tag: df6859d606f8d04cb80d0a5361dc3a910d476edb
podAnnotations:
  linkerd.io/inject: enabled
ingress:
  enabled: true
  className: nginx
  hosts:
  - host: devapp.ganba.local
    paths:
    - path: /
      pathType: ImplementationSpecific
