apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echoserver
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/david-bour/local-gitops.git
    path: argocd-applications/cluster-dependencies/charts/echoserver
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: echoserver
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
