apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- path: ./ingress.yml
  target:
    kind: Ingress
images:
- name: davidbour/echoserver
  newTag: df6859d606f8d04cb80d0a5361dc3a910d476edb
